### ISSUE TITLE
Error "Input vector should be 1-D" when generating mesh.

### ISSUE THREAD

**Issue by cgotelli** [VeinsOfTheEarth/RivGraph#87]
Hello!

I'm trying to use Rivgraph to process the results of a braided river simulation (similar to what you did in the Tejedor (2022) article). I'm following a combination of the steps shown in the three available examples, and so far I've the network shown below (I manually disabled the labels for nodes and links).

![Example network](https://user-images.githubusercontent.com/96237432/195561826-3aa035ed-f229-4e54-be71-94343f9d776e.png)

The problem I am facing is that I get an error when I use the `compute_mesh()` function. It seems to be a problem with a distance calculation, but I can't fully understand it. I would really appreciate any feedback or recommendations on how to proceed to get it working.

If it's helpful, here's the error detail:

```python 
Traceback (most recent call last):

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/mnt/data1/GITHUB/Iber4Rivgraph/main.py", line 30, in <module>
    links, nodes = f.getNetwork(RastersPath)

  File "/mnt/data1/GITHUB/Iber4Rivgraph/functions.py", line 173, in getNetwork
    braidedRiver.compute_mesh()

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/rivgraph/classes.py", line 856, in compute_mesh
    self.meshlines, self.meshpolys, self.centerline_smooth = ru.valleyline_mesh(self.centerline, self.avg_chan_width, buf_halfwidth, grid_spacing, smoothing=smoothing)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/rivgraph/rivers/river_utils.py", line 769, in valleyline_mesh
    llines, lmap = iterative_cl_pt_mapping(cl2, bdists, 'left')

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/rivgraph/rivers/river_utils.py", line 608, in iterative_cl_pt_mapping
    distance, path = fastdtw(Ao, An, dist=euclidean)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/fastdtw/fastdtw.py", line 53, in fastdtw
    return __fastdtw(x, y, radius, dist)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/fastdtw/fastdtw.py", line 73, in __fastdtw
    __fastdtw(x_shrinked, y_shrinked, radius=radius, dist=dist)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/fastdtw/fastdtw.py", line 73, in __fastdtw
    __fastdtw(x_shrinked, y_shrinked, radius=radius, dist=dist)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/fastdtw/fastdtw.py", line 73, in __fastdtw
    __fastdtw(x_shrinked, y_shrinked, radius=radius, dist=dist)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/fastdtw/fastdtw.py", line 73, in __fastdtw
    __fastdtw(x_shrinked, y_shrinked, radius=radius, dist=dist)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/fastdtw/fastdtw.py", line 68, in __fastdtw
    return dtw(x, y, dist=dist)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/fastdtw/fastdtw.py", line 130, in dtw
    return __dtw(x, y, None, dist)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/fastdtw/fastdtw.py", line 141, in __dtw
    dt = dist(x[i-1], y[j-1])

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/scipy/spatial/distance.py", line 518, in euclidean
    return minkowski(u, v, p=2, w=w)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/scipy/spatial/distance.py", line 461, in minkowski
    u = _validate_vector(u)

  File "/home/epfl-lhe/mambaforge/envs/Iber4Rivgraph/lib/python3.9/site-packages/scipy/spatial/distance.py", line 301, in _validate_vector
    raise ValueError("Input vector should be 1-D.")

ValueError: Input vector should be 1-D.
```

**Comment by cgotelli** [comment]
Hello @jonschwenk!
Thank you very much for your response. I did what you suggest but with a mesh I made with QGis, and it worked perfectly! I will continue working to get other topologic metrics with the outputs of RG, so I might bother you again :sweat_smile: 
Thanks again!
